version: '3'

networks:
  default:
    driver: bridge

services:

  jupyter:
    container_name: jupyter
    image: jupyter:latest
    build:
      context: ./
      args:
        NB_UID: 1000
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/notebooks
    restart: "no"
