version: '3'

networks:
  default:
    driver: bridge

services:

  jupyter:
    container_name: jupyter
    image: jupyter:latest
    build:
      context: ./
      args:
        NB_UID: 1000
    ports:
      - "8090:8888"
    volumes:
      - ./jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
      - ./data:/home/jovyan/data
    #restart: always
    depends_on:
      - vroom
